### ISSUE TITLE
Implement a search bar

### ISSUE THREAD

**Issue by dariolina** [subspace/subnomicon#9]

**Comment by SethY8s** [comment]
Hey, I think I could do this pretty easily, how complex are you thinking? I have experience with elastic search and Algolia if it is on the more complicated side.

**Comment by dariolina** [comment]
Hi @SethY8s, anything simple supported by docusaurus works, I think. It should be able to search word appearances like "replotting" on different pages and that it. PRs or any suggestions are welcome!

**Comment by SethY8s** [comment]
Hey @dariolina I got the search bar working. One last thing I need is Algolia's API keys. I figured since I am not a maintainer of this open-source project, I would let you fill that out here.

[https://docsearch.algolia.com/apply/](url)

I am going to make a pretty bare-bones PR with the minor changes I added, but if you run my branch locally, you will see the search bar and the modal popup working. That being said without the API keys, the search bar will not function properly. If you give me permission I could try to get these public Algolia API keys, but figured I would ask you first.

Also, I am going to bed right now, so I won't be able to make any changes until tomorrow. Thanks

**Comment by dariolina** [comment]
@SethY8s Thank you for letting me know! I will take a look

**Comment by SethY8s** [comment]
@dariolina Yeah just let me know if you get the keys and either of us could add it and merge it in. If there's anything else, I'd be glad to help!

**Comment by dariolina** [comment]
@SethY8s I have applied for the DocSearch, will let you know when I set up the indexer! Probably next week

**Comment by dariolina** [comment]
Closed by #12
